import * as React from "react"
import Layout from "../components/layout"
import Seo from "../components/seo"
import * as styles from "../components/index.module.css"

const IndexPage = () => {
  const [formData, setFormData] = React.useState({
      name: "",
          discord: "",
              department: "",
                  experience: "",
                    })
                      const [status, setStatus] = React.useState(null)

                        const handleChange = e => {
                            setFormData({ ...formData, [e.target.name]: e.target.value })
                              }

                                const handleSubmit = async e => {
                                    e.preventDefault()
                                        setStatus("Submitting...")

                                            try {
                                                  const res = await fetch("/submit", {
                                                          method: "POST",
                                                                  headers: { "Content-Type": "application/json" },
                                                                          body: JSON.stringify(formData),
                                                                                })
                                                                                      if (res.ok) setStatus("✅ Submitted successfully!")
                                                                                            else throw new Error("Failed to submit.")
                                                                                                } catch {
                                                                                                      setStatus("❌ Something went wrong.")
                                                                                                          }
                                                                                                            }

                                                                                                              return (
                                                                                                                  <Layout>
                                                                                                                        <div className={styles.portalContainer}>
                                                                                                                                <header className={styles.header}>
                                                                                                                                          <h1 className={styles.title}>NYSRP Portal</h1>
                                                                                                                                                    <p className={styles.subtitle}>by Shadow Ranger</p>
                                                                                                                                                            </header>

                                                                                                                                                                    <section className={styles.section}>
                                                                                                                                                                              <h2 className={styles.sectionTitle}>Department Application</h2>
                                                                                                                                                                                        <form onSubmit={handleSubmit} className={styles.form}>
                                                                                                                                                                                                    <input
                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                name="name"
                                                                                                                                                                                                                                              placeholder="Your Name"
                                                                                                                                                                                                                                                            value={formData.name}
                                                                                                                                                                                                                                                                          onChange={handleChange}
                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                                                                                            name="discord"
                                                                                                                                                                                                                                                                                                                                                          placeholder="Discord Tag (e.g. Ranger#1234)"
                                                                                                                                                                                                                                                                                                                                                                        value={formData.discord}
                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                            <select
                                                                                                                                                                                                                                                                                                                                                                                                                                          name="department"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={formData.department}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="">Select Department</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="Police">Police</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="Fire & EMS">Fire & EMS</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="DOT">DOT</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="Civilian">Civilian</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name="experience"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Briefly describe your RP experience"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={formData.experience}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="submit" className={styles.glowButton}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Submit Application
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {status && <p className={styles.status}>{status}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <section className={styles.section}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className={styles.sectionTitle}>Useful Links</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className={styles.links}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="https://discord.gg/nysummer" target="_blank" rel="noreferrer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Join Discord
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="https://discord.com/channels/1418777099593846879/1418777100793544805" target="_blank" rel="noreferrer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Documentation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export const Head = () => <Seo title="NYSRP Portal" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default IndexPage
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        